import "dotenv/config";
import crypto from "crypto";
import mongoose from "mongoose";
import QRCode from "qrcode";
import Asset from "../models/Asset.js";

const addDays = (date, days) => {
  const nextDate = new Date(date);
  nextDate.setDate(nextDate.getDate() + days);
  return nextDate;
};

const today = new Date();
const scannerBase = "http://localhost:7000/api/scan";

const sampleAssets = [
  {
    assetName: "Dell Latitude 5440",
    category: "Laptop",
    subCategory: "Business Laptop",
    assetStatus: "ASSIGNED",
    assignedTo: "Meet Patel",
    serialNumber: "DL-5440-0001",
    assetCode: "AMS-SAMPLE-001",
    brand: "Dell",
    model: "Latitude 5440",
    assetType: "Laptop",
    purchaseDate: addDays(today, -220),
    vendor: "Dell India",
    warrantyPeriod: 36,
    maintenancePeriod: 6,
    price: 68500,
    invoiceNumber: "INV-SAMPLE-001",
    warrantyStart: addDays(today, -220),
    warrantyEnd: addDays(today, 875),
    warrantyReminderDays: 30,
    officeName: "Head Office",
    branchCode: "HO-001",
    floor: "3rd Floor",
    department: "IT",
    room: "IT Bay",
    city: "Ahmedabad",
    state: "Gujarat",
    officeContactPerson: "Priyam",
    officePhone: "9876543210",
    assignedDate: addDays(today, -20),
    employeeId: "EMP-006",
    employeeEmail: "meet.patel@example.com",
    assignedBy: "Priyam",
    ipAddress: "192.168.1.51",
    macAddress: "AA:BB:CC:DD:EE:01",
    hostName: "AMS-LAP-001",
    networkType: "WiFi",
    subnet: "255.255.255.0",
    gateway: "192.168.1.1",
    operatingSystem: "Windows 11 Pro",
    processor: "Intel Core i5",
    ram: "16 GB",
    storage: "512 GB SSD",
    antivirus: "Microsoft Defender",
    domainName: "assetpro.local",
    assetDescription: "Sample assigned laptop with Asset Type filled.",
    deviceOwnedBy: "Me",
  },
  {
    assetName: "HP EliteDesk 800 G6",
    category: "Desktop",
    subCategory: "Office Desktop",
    assetStatus: "AVAILABLE",
    serialNumber: "HP-800G6-0002",
    assetCode: "AMS-SAMPLE-002",
    brand: "HP",
    model: "EliteDesk 800 G6",
    assetType: "Desktop",
    purchaseDate: addDays(today, -390),
    vendor: "HP Partner",
    warrantyPeriod: 24,
    maintenancePeriod: 6,
    price: 52000,
    invoiceNumber: "INV-SAMPLE-002",
    warrantyStart: addDays(today, -390),
    warrantyEnd: addDays(today, 340),
    warrantyReminderDays: 45,
    officeName: "Head Office",
    branchCode: "HO-001",
    floor: "2nd Floor",
    department: "Admin",
    room: "Store Room",
    city: "Ahmedabad",
    state: "Gujarat",
    officeContactPerson: "Admin Desk",
    officePhone: "9876501234",
    ipAddress: "192.168.1.52",
    macAddress: "AA:BB:CC:DD:EE:02",
    hostName: "AMS-DESK-002",
    networkType: "LAN",
    subnet: "255.255.255.0",
    gateway: "192.168.1.1",
    operatingSystem: "Windows 10 Pro",
    processor: "Intel Core i7",
    ram: "16 GB",
    storage: "1 TB HDD",
    antivirus: "Quick Heal",
    domainName: "assetpro.local",
    assetDescription: "Sample available desktop asset.",
    deviceOwnedBy: "Me",
  },
  {
    assetName: "Canon LBP 2900 Printer",
    category: "Printer",
    subCategory: "Laser Printer",
    assetStatus: "UNDER_REPAIR",
    assignedTo: "Admin Department",
    serialNumber: "CN-LBP-0003",
    assetCode: "AMS-SAMPLE-003",
    brand: "Canon",
    model: "LBP 2900",
    assetType: "Printer",
    purchaseDate: addDays(today, -760),
    vendor: "Canon Partner",
    warrantyPeriod: 12,
    maintenancePeriod: 3,
    price: 14500,
    invoiceNumber: "INV-SAMPLE-003",
    warrantyStart: addDays(today, -760),
    warrantyEnd: addDays(today, -395),
    warrantyReminderDays: 15,
    officeName: "Branch Office",
    branchCode: "BR-002",
    floor: "1st Floor",
    department: "Admin",
    room: "Print Area",
    city: "Surat",
    state: "Gujarat",
    officeContactPerson: "Ravi Shah",
    officePhone: "9123456780",
    assignedDate: addDays(today, -180),
    assignedBy: "IT Admin",
    assetDescription: "Sample printer under repair with expired warranty.",
    deviceOwnedBy: "Me",
    repairHistory: [
      {
        ticketId: "REP-SAMPLE-003",
        issue: "Paper Jam",
        priority: "High",
        description: "Frequent paper jam during printing.",
        repairDate: addDays(today, -2),
        repairCost: 1200,
        repairDetails: "Roller replacement pending.",
        vendorName: "Canon Service",
        status: "OPEN",
        updatedBy: "IT Staff",
      },
    ],
  },
  {
    assetName: "Samsung 24 Inch Monitor",
    category: "Monitor",
    subCategory: "LED Monitor",
    assetStatus: "ASSIGNED",
    assignedTo: "Neha Sharma",
    serialNumber: "SM-MON-0004",
    assetCode: "AMS-SAMPLE-004",
    brand: "Samsung",
    model: "S24F350",
    assetType: "Monitor",
    purchaseDate: addDays(today, -120),
    vendor: "Local IT Store",
    warrantyPeriod: 24,
    maintenancePeriod: 12,
    price: 9800,
    invoiceNumber: "INV-SAMPLE-004",
    warrantyStart: addDays(today, -120),
    warrantyEnd: addDays(today, 610),
    warrantyReminderDays: 30,
    officeName: "Head Office",
    branchCode: "HO-001",
    floor: "4th Floor",
    department: "Finance",
    room: "Finance Bay",
    city: "Ahmedabad",
    state: "Gujarat",
    officeContactPerson: "Neha Sharma",
    officePhone: "9988776655",
    assignedDate: addDays(today, -80),
    employeeId: "EMP-018",
    employeeEmail: "neha.sharma@example.com",
    assignedBy: "Priyam",
    assetDescription: "Sample monitor assigned to employee.",
    deviceOwnedBy: "Me",
  },
  {
    assetName: "Cisco SG350 Network Switch",
    category: "Network",
    subCategory: "Switch",
    assetStatus: "AVAILABLE",
    serialNumber: "CS-SG350-0005",
    assetCode: "AMS-SAMPLE-005",
    brand: "Cisco",
    model: "SG350-28",
    assetType: "Network Device",
    purchaseDate: addDays(today, -500),
    vendor: "Cisco Partner",
    warrantyPeriod: 36,
    maintenancePeriod: 6,
    price: 32000,
    invoiceNumber: "INV-SAMPLE-005",
    warrantyStart: addDays(today, -500),
    warrantyEnd: addDays(today, 595),
    warrantyReminderDays: 60,
    officeName: "Data Center",
    branchCode: "DC-001",
    floor: "Ground Floor",
    department: "IT Infrastructure",
    room: "Server Room",
    city: "Ahmedabad",
    state: "Gujarat",
    officeContactPerson: "Infra Team",
    officePhone: "9090909090",
    assetDescription: "Sample network device for available inventory.",
    deviceOwnedBy: "Other",
    ownerName: "AssetPro IT Team",
  },
];

await mongoose.connect(process.env.MONGO_URL);

const savedAssets = [];

for (const sampleAsset of sampleAssets) {
  const existingAsset = await Asset.findOne({ assetCode: sampleAsset.assetCode });
  const qrToken = existingAsset?.qrToken || crypto.randomBytes(16).toString("hex");
  const asset = await Asset.findOneAndUpdate(
    { assetCode: sampleAsset.assetCode },
    {
      $set: {
        ...sampleAsset,
        qrToken,
        lifecycleTimeline: [
          ...(existingAsset?.lifecycleTimeline || []),
          {
            title: existingAsset ? "Sample Data Updated" : "Sample Data Added",
            detail: `${sampleAsset.assetName} sample record is ready for testing.`,
            date: today,
          },
        ],
      },
    },
    { returnDocument: "after", upsert: true, setDefaultsOnInsert: true },
  );

  asset.qrCode = await QRCode.toDataURL(`${scannerBase}/${asset._id}?t=${asset.qrToken}`, {
    errorCorrectionLevel: "H",
    margin: 2,
    width: 300,
  });
  await asset.save();

  savedAssets.push({
    assetCode: asset.assetCode,
    assetName: asset.assetName,
    assetType: asset.assetType,
    status: asset.assetStatus,
  });
}

console.log(
  JSON.stringify(
    {
      database: mongoose.connection.name,
      upserted: savedAssets.length,
      assets: savedAssets,
    },
    null,
    2,
  ),
);

await mongoose.disconnect();
