export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard.view",
  ASSET_VIEW: "asset.view",
  ASSET_CREATE: "asset.create",
  ASSET_EDIT: "asset.edit",
  ASSET_DELETE: "asset.delete",
  ASSET_ASSIGN: "asset.assign",
  QR_GENERATE: "qr.generate",
  QR_SCAN: "qr.scan",
  REQUEST_VIEW: "request.view",
  REQUEST_CREATE: "request.create",
  REQUEST_APPROVE: "request.approve",
  REQUEST_REJECT: "request.reject",
  INVENTORY_VIEW: "inventory.view",
  INVENTORY_MANAGE: "inventory.manage",
  MAINTENANCE_VIEW: "maintenance.view",
  MAINTENANCE_MANAGE: "maintenance.manage",
  WARRANTY_VIEW: "warranty.view",
  WARRANTY_MANAGE: "warranty.manage",
  EMPLOYEE_PORTAL: "employee.portal",
  USER_MANAGE: "user.manage",
  OFFICE_VIEW: "office.view",
  OFFICE_MANAGE: "office.manage",
  REPORT_VIEW: "report.view",
  REPORT_EXPORT: "report.export",
  AUDIT_VIEW: "audit.view",
  AUDIT_MANAGE: "audit.manage",
  SYSTEM_SETTINGS: "system.settings",
};

export const DEFAULT_ROLE_PERMISSIONS = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_CREATE,
    PERMISSIONS.ASSET_EDIT,
    PERMISSIONS.ASSET_DELETE,
    PERMISSIONS.ASSET_ASSIGN,
    PERMISSIONS.QR_GENERATE,
    PERMISSIONS.QR_SCAN,
    PERMISSIONS.REQUEST_VIEW,
    PERMISSIONS.REQUEST_APPROVE,
    PERMISSIONS.REQUEST_REJECT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.WARRANTY_VIEW,
    PERMISSIONS.WARRANTY_MANAGE,
    PERMISSIONS.EMPLOYEE_PORTAL,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.OFFICE_VIEW,
    PERMISSIONS.OFFICE_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
  ],
  IT_STAFF: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_CREATE,
    PERMISSIONS.ASSET_EDIT,
    PERMISSIONS.ASSET_ASSIGN,
    PERMISSIONS.QR_GENERATE,
    PERMISSIONS.QR_SCAN,
    PERMISSIONS.REQUEST_VIEW,
    PERMISSIONS.REQUEST_CREATE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.WARRANTY_VIEW,
    PERMISSIONS.REPORT_VIEW,
  ],
  MANAGER: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.REQUEST_VIEW,
    PERMISSIONS.REQUEST_APPROVE,
    PERMISSIONS.REQUEST_REJECT,
    PERMISSIONS.REPORT_VIEW,
  ],
  EMPLOYEE: [
    PERMISSIONS.EMPLOYEE_PORTAL,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.REQUEST_CREATE,
    PERMISSIONS.REQUEST_VIEW,
    PERMISSIONS.WARRANTY_VIEW,
    PERMISSIONS.QR_SCAN,
  ],
  AUDITOR: [
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.ASSET_VIEW,
  ],
};

export const DEFAULT_ROLE_SIDEBAR = {
  SUPER_ADMIN: [
    "Dashboard",
    "Assets",
    "Masters",
    "QR Console",
    "Requests",
    "Inventory",
    "Employee Portal",
    "Assignments",
    "Maintenance",
    "Warranty",
    "Offices",
    "Audit Session",
    "Reports",
    "Users & Access",
  ],
  ADMIN: [
    "Dashboard",
    "Assets",
    "Masters",
    "QR Console",
    "Requests",
    "Inventory",
    "Employee Portal",
    "Assignments",
    "Maintenance",
    "Warranty",
    "Offices",
    "Audit Session",
    "Reports",
    "Users & Access",
  ],
  IT_STAFF: [
    "Dashboard",
    "Assets",
    "QR Console",
    "Requests",
    "Inventory",
    "Assignments",
    "Maintenance",
    "Warranty",
    "Reports",
  ],
  MANAGER: ["Dashboard", "Assets", "Requests", "Reports"],
  EMPLOYEE: ["Employee Portal", "Requests", "Warranty", "QR Console"],
  AUDITOR: ["Audit Session", "Reports", "Assets"],
};
